### ISSUE TITLE
Data Preprocessing Steps and AlphaSpace Errors

### ISSUE THREAD

**Issue by 545487677** [bytedance/DecompDiff#4]
Hello,

If I want to perform data preprocessing, which data should I use, and what are the steps to process it?

I have been using the crossdocked_v1.1_rmsd1.0 data for preprocessing, but I keep encountering the following message:

AlphaSpace run fail!

If it’s convenient for you, could you help me with this issue?

**Comment by 545487677** [comment]
1

**Comment by QiaolinLu** [comment]
I also encountered this question, have you fixed it, or could you please provide the data link of crossdocked_v1.1_rmsd1.0? Really thanks!
